# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('Name', 'Name'), ('Root', 'Root')], default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TreePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('node_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admintree.TreeNode')),
                ('node_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admintree.TreeNode')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintree.Tree')),
            ],
        ),
        migrations.AddField(
            model_name='treenode',
            name='child',
            field=models.ManyToManyField(through='admintree.TreePath', to='admintree.TreeNode'),
        ),
        migrations.AddField(
            model_name='tree',
            name='start_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admintree.TreeNode'),
        ),
    ]
